### ISSUE TITLE
ETL start niet door ontbreken "picklegit" Python module

### ISSUE THREAD

**Issue by justb4** [Geonovum/smartemission#11]
Na de commit eb7f8e1a8a182618fbf5dcae6aecd20bd765f47 starten de ETL processen niet meer. Zie onder. Mogelijk ontbrekend package/module, maar welke? Moet in Stetl Docker file toegevoegd. 

```
2016-07-21 11:42:01,574 main INFO Stetl version = 1.1.0rc1
2016-07-21 11:42:01,575 main INFO Found args file at: options/docker.args
2016-07-21 11:42:01,576 ETL INFO INIT - Stetl version is 1.1.0rc1
2016-07-21 11:42:01,576 ETL INFO Config/working dir = /opt/geonovum/smartem/git/etl
2016-07-21 11:42:01,576 ETL INFO Reading config_file = last.cfg
.
.
2016-07-21 11:42:01,576 ETL INFO START
2016-07-21 11:42:01,576 util INFO Timer start: total ETL
2016-07-21 11:42:01,576 chain INFO Assembling Chain: input_raw_sensor_last_api|output_postgres_insert...
2016-07-21 11:42:01,601 factory ERROR cannot create class 'rawsensorapi.RawSensorLastInput'
2016-07-21 11:42:01,601 factory ERROR cannot create object instance from class 'rawsensorapi.RawSensorLastInput' e=No module named picklegit
Traceback (most recent call last):
  File "/usr/local/bin/stetl", line 5, in <module>
    pkg_resources.run_script('Stetl==1.1.0rc1', 'stetl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Stetl-1.1.0rc1-py2.7.egg/EGG-INFO/scripts/stetl", line 40, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/Stetl-1.1.0rc1-py2.7.egg/EGG-INFO/scripts/stetl", line 31, in main
    etl.run()
  File "/usr/local/lib/python2.7/dist-packages/Stetl-1.1.0rc1-py2.7.egg/stetl/etl.py", line 98, in run
    chain.assemble()
  File "/usr/local/lib/python2.7/dist-packages/Stetl-1.1.0rc1-py2.7.egg/stetl/chain.py", line 42, in assemble
    etl_comp = factory.create_obj(self.config_dict, etl_section_name)
  File "/usr/local/lib/python2.7/dist-packages/Stetl-1.1.0rc1-py2.7.egg/stetl/factory.py", line 29, in create_obj
    raise e
ImportError: No module named picklegit

```

**Comment by justb4** [comment]
Ok, opgelost via commit 097d4289ed8988bf02e60117ec6f5292f0a3f83a (comment daar klopt niet), was waarschijnlijk typo.
